### ISSUE TITLE
Error using macro to generate `contract-out`

### ISSUE THREAD

**Issue by bennn** [philnguyen/soft-contract#101]
#### Example Program

```
#lang racket/base
(require racket/contract)

(define-syntax-rule (define2 x ctc e)
  (begin
    (define x e)
    (provide (contract-out [x ctc]))))

(define2 g (between/c 1 10) 8)
```

#### Error Message

Running `raco scv`gives

```
between/c: unbound identifier in module
  context...:
   #(4611 module) #(4612 module foo 0) #(5759 use-site) #(5819 local) #(5820 intdef)
  other binding...:
   #<module-path-index:(soft-contract/fake-contract)>
   #(-60935756105263110 module)
   #(-60935756105263109 module expand-keep-contracts 0) #(4611 module)
   #(4612 module foo 0)
  in: between/c
```

#### Note

The same problem happens with the `zordoz` gradual typing benchmark, because the `compiler/zo-structs` module uses a macro to generate `contract-out`s.

Minimal example:

```
#lang racket/base
(require compiler/zo-structs)

(zo? #f)
```

**Comment by philnguyen** [comment]
I realized `zo` stuff didn't work yet. I'll just declare a bunch of contracts for them as primitives in a bit.

**Comment by bennn** [comment]
https://github.com/philnguyen/soft-contract/commit/81618e77d41bb57175741f3a172b375c6d076567 doesn't build (cannot find file `prims-zo.rkt`)

**Comment by bennn** [comment]
great!
