### ISSUE TITLE
question: why isn't this program safe?

### ISSUE THREAD

**Issue by bennn** [philnguyen/soft-contract#102]
I expected this program would be safe, but it isn't:

```
#lang racket

(define (deep n)
  (if (zero? n) n (list (deep (- n 1)))))

(define my-ctc
  (or/c exact-nonnegative-integer?
        (list/c (recursive-contract my-ctc #:chaperone))))

(provide
  (contract-out
    (deep (-> exact-nonnegative-integer? my-ctc))))
```

`raco scv` says:

```
(blame
 (line 7 col 2)
 (violator
  :
  "/Users/ben/code/racket/my-pkgs/require-typed-scv/test/gtp/zombie/test.rkt")
 (contract
  from
  :
  "/Users/ben/code/racket/my-pkgs/require-typed-scv/test/gtp/zombie/test.rkt")
 (contracts : cons?)
 (values : ●_exact-integer?_zero?))
```

The program is "Safe" if I change `my-ctc` to use `integer?` instead of `exact-nonnegative-integer?`.

**Comment by philnguyen** [comment]
It looks like it doesn't know that `exact-integer?` and `zero?` implies `exact-nonnegative-integer?`. I have very hacky inferences on multiple base predicates that I should refactor and generalize. I'll fix this in a bit.

It should be able to prove a stronger base case of `and/c number? zero?` in this case (or just `0`)
