### ISSUE TITLE
How to install and use soft-contract?

### ISSUE THREAD

**Issue by LaifsV1** [philnguyen/soft-contract#108]
I followed the instructions in the README by running `raco pkg install`. The package `soft-contract` is installed with the message: `raco pkg install: packages installed, although setup reported errors`

I then try to run it on the example `raco scv test/programs/safe/octy/ex-14.rkt`, but get the following message:
```
utils/map.rkt:11:7: for/seteq:: unbound identifier
  in: for/seteq:
  location...:
   utils/map.rkt:11:7
  context...:
   do-raise-syntax-error
   expand-implicit
   for-loop
   finish-bodys
   lambda-clause-expander
   loop
   [repeats 5 more times]
   module-begin-k
   do-local-expand50
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/tc-setup.rkt:94:0: tc-module/full
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typed-racket.rkt:23:4: module-begin
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   ensure-module-begin34
   expand-module16
   ...
```

What is the issue here? Did I install the package incorrectly?

**Comment by bennn** [comment]
What version of Racket are you using --- is it something earlier than 6.5?

**Comment by LaifsV1** [comment]
I'm using Racket v7.2.

**Comment by camoy** [comment]
Try installing from the `dev-adi` branch which is more up to date. Recent developments have not been merged into master.

**Comment by LaifsV1** [comment]
I just cloned `dev-adi` and installed soft-contract as per the instructions.
I tried to run a test `raco scv soft-contract/test/programs/unsafe/softy/recursive-div2.rkt` but still get the following message:
```
soft-contract/utils/map.rkt:11:7: for/seteq:: unbound identifier
  in: for/seteq:
  location...:
   soft-contract/utils/map.rkt:11:7
  context...:
   do-raise-syntax-error
   expand-implicit
   for-loop
   finish-bodys
   lambda-clause-expander
   loop
   [repeats 5 more times]
   module-begin-k
   do-local-expand50
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/tc-setup.rkt:94:0: tc-module/full
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typed-racket.rkt:23:4: module-begin
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   ensure-module-begin34
   expand-module16
```

**Comment by camoy** [comment]
Make sure you have the [typed-racket-hacks](https://github.com/philnguyen/typed-racket-hacks) package installed.

**Comment by LaifsV1** [comment]
I installed `type-racket-hacks`, but still get the same message. I tried reinstalling `soft-contract` after installing `type-racket-hacks`.

**Comment by bennn** [comment]
That file compiles for me after installing `typed-racket-hacks`.
This smaller one works too (and fails if the `require` line is missing.)
```
#lang typed/racket/base
(require typed-racket-hacks)
(for/seteq : (Setof Symbol) ((x '(a b c))) x)
```

**Comment by LaifsV1** [comment]
I tried compiling the program above, and I get the same error message containing:
```
for/seteq:: unbound identifier
  in: for/seteq:
  location...:
   soft-contract/soft-contract/utils/map.rkt:11:7
```
My list of installed packages is:
```
raco pkg show
Installation-wide:
 Package            Checksum             Source
 main-distribution  4d09880d797bd4f1...  catalog...tribution
 racket-lib         368ea6923f22d9a5...  catalog racket-lib
 [195 auto-installed packages not shown]
User-specific for installation "7.2":
 Package             Checksum             Source
 experiment                               link...i/experiment
 rosette             fd9d1576527cca0b...  catalog...a/rosette
 soft-contract                            link...oft-contract
 typed-racket-hacks  6d462852a29abb44...  catalog...ket-hacks
 [26 auto-installed packages not shown]
```
I've tried other tools for Racket and they work correctly, so I don't think it's my installation.

**Comment by bennn** [comment]
Are you sure you're using the same `raco` to compile the program?

I just tried with a 7.2 release and the program above works after I install `typed-racket-hacks` and `set-extras`

**Comment by LaifsV1** [comment]
I only have one `raco` in my path. I didn't have `set-extras` installed, but even with it, I still cannot compile the example.

**Comment by bennn** [comment]
How did you install `typed-racket-hacks` without getting `set-extras`!?

Are you using `raco pkg install ....` to install packages, or something else?

**Comment by LaifsV1** [comment]
Sorry, I'm not very familiar with Racket. I'm using `raco pkg install ...` as in the instructions in the README for `typed-racket-hacks`. It might have been installed as a dependency, but I didn't see it so I just installed it manually right now anyway.

**Comment by bennn** [comment]
Can you share the terminal output from when you installed set-extras manually?

I'd expect to see something about it being promoted "from auto-installed to explicitly installed" or about it already being installed.
- If not, then I can try to help figure out what's wrong.
- If it does say that, then I don't learn anything new and I guess I recommend that you download a new copy of 7.2, try `raco pkg install typed-racket-hacks`, and then compile the program above. (Not sure what else to suggest)

**Comment by LaifsV1** [comment]
Ah, it did say `from auto-installed to explicitly installed`. I'll try reinstalling 7.2 again.

**Comment by LaifsV1** [comment]
Ah, I got it working. I installed 7.5 instead of using apt get, but I don't think this was the issue. There might have been something wrong with my installation. Thanks!

**Comment by LaifsV1** [comment]
Just to close this in a meaningful way, here's the things that helped:

- Needs Racket 6.5 and over
- Use branch `dev-adi`
- Install `typed-racket-hacks` with `set-extras`
- Reinstalling Racket

The most important points being `dev-adi` and `typed-racket-hacks`, which I wouldn't have figured out on my own.
