### ISSUE TITLE
Support unsafe-vector* operations

### ISSUE THREAD

**Issue by camoy** [philnguyen/soft-contract#121]
Is there are a good way to support `unsafe-vector*-length`, `unsafe-vector*-ref`, `unsafe-vector*-set!`? These are present in the expansion of, I believe synth. I had previously aliased these to `vector-length`, etc. but now that I think about that it's unsound since it doesn't restrict the vector argument to non-impersonators. However, I'm not sure SCV has any mechanisms for dealing with that restriction.

**Comment by samth** [comment]
You could define versions that check for impersonators and error. I think the actual generated code probably has those checks.
