### ISSUE TITLE
succ test

### ISSUE THREAD

**Issue by sorawee** [philnguyen/soft-contract#128]
As I understand, https://github.com/philnguyen/soft-contract/blob/master/soft-contract/test/programs/paper/succ.rkt should be verified, right? Currently it generates an error:

```
    - Expected: {(λ (cmp_2424) …)}
    - Given: {●integer?_(≥/c 0)}
```

The test seems to get disabled in https://github.com/philnguyen/soft-contract/commit/3eb1c7c608c539affd60e8a7a2c8130b09a7de09.

**Comment by philnguyen** [comment]
Yea when I dropped Z3 a few tests failed, so I disabled them planning to revisit later ^_^

**Comment by sorawee** [comment]
Ah I see! Thanks for the reply. I will close this issue then.

By the way, I tried the `jfp` branch, and the `succ.rkt` example works perfectly.

On the other hand, here's a program that doesn't work:

```
(module test racket
  (provide (contract-out [test ((and/c integer? in?) . -> . out?)]))
  (define (out? x)
    (= x 9))
  (define (in? x)
    (= 10 (add1 x)))
  (define (test x)
    x))
```

Could it be made to work?
