### ISSUE TITLE
Timeout on simple recursive function

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#15]
```
(module div racket
  (provide (contract-out [divides? (-> positive? positive? boolean?)]))

  (define (positive? x)
    (and (integer? x) (<= 0 x)))
  
  (define (divides? a b)
    (if (= 0 b) #t
        (if (< b a) 
            #f
            (divides? a (- b a))))))
```

**Comment by dvanhorn** [comment]
Here's an even simpler recursive program that times out:
```
(module m racket
  (provide (contract-out [f (c? . -> . c?)]))
  (define (c? x) (and (integer? x) (> x 10)))
  (define (f x) (f (+ x x))))
```
if you change `(and (integer? x) (> x 10))` to `(integer? x)` it works fine.

**Comment by cmentzer** [comment]
Was this issue resolved? I've got a simple recursive program that times out
after 20 seconds, and I don't want to submit a redundant issue.

**Comment by dvanhorn** [comment]
The web server is up to date, so if it times out there, it's a (new) bug.

**Comment by cmentzer** [comment]
Ok, I'm talking to Phil on gchat (hangouts) about it right now.
