### ISSUE TITLE
Bogus Counterexample

### ISSUE THREAD

**Issue by cmentzer** [philnguyen/soft-contract#4]
This is a similar problem to what DVH posted on Wednesday, where the verifier will produce a counterexample that does not actually cause an error when there are counterexamples that would provide errors.

```
    (module foo racket
      (provide (contract-out [foo (string? . -> . (or/c string? integer?))]))
      (define (foo s)
            (/ (string-length s) 2)))
```

foo takes a string and returns the length of the string divided by 2, and expects the result to be an integer. This is obviously not safe because any string with an odd number of characters divided by 2 will not yield an integer. 

However, the verifier seems to always provide counterexamples where the string is of even length, as below:

```
    Contract violation: 'foo' violates its own contract.
    Value
     0.5
    violates predicate
    integer? 
    An example module that breaks it:
     (module user racket (require (submod ".." foo)) (foo "XsUM5f"))
```

It is worth noting that this only happens when the code is unsafe -- which means that the verifier is correctly identifying unsafe programs, but not providing correct counterexamples.

**Comment by philnguyen** [comment]
I fixed it to generate the right counterexample now:
```
Contract violation: 'foo' violates its own contract.
Value
 0.5
violates predicate
 integer?
An example module that breaks it:
 (module user racket (require (submod ".." foo)) (foo "T"))
```


 There's currently a mis-match between the Z3 translation and Racket's  numeric tower, so the error message is still wrong. In this case, the actual value that violates `integer?` is `1/2`, not `0.5`.

**Comment by philnguyen** [comment]
(The remaining half-problem was reported as a separate issue)
