### ISSUE TITLE
Eliminate fake contracts

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#40]
This will involve working with Robby to have contracts library provide the information that fake contracts provide.

**Comment by bennn** [comment]
Are fake contracts eliminated?

I think they are, because running `raco scv file.rkt` claims this program is safe --- and the program doesn't use fake contracts:
```
#lang racket

(define (triangle n)
  (quotient (* n (+ n 1)) 2))

(provide
  (contract-out (triangle (-> integer? integer?))))
```

**Comment by philnguyen** [comment]
They are now. It's gross behind the scene. But you shouldn't have modify the files anymore.
