### ISSUE TITLE
Verifier Incorrectly Claims Safety

### ISSUE THREAD

**Issue by cmentzer** [philnguyen/soft-contract#5]
The following module is considered to be "safe" by the verifier, where foo takes a function that operates on two integers and an integer and then applies the given function to the given number and 5. 
```
(module foo racket
  (provide (contract-out 
            [foo ((integer? integer? . -> . integer?) integer? . -> . integer?)]))
  (define (foo f n)
    (f n 5)))
```
But there is an obvious counterexample of passing foo division.
```
(require 'foo) 
(foo / 2)
```
Which gives the following error:
```
foo: contract violation
  expected: integer?
  given: 2/5
  in: the range of
      the 1st argument of
      (->
       (-> integer? integer? integer?)
       integer?
       integer?)
  contract from: foo
  blaming: program
   (assuming the contract is correct)
  at: eval:1.43
```

**Comment by dvanhorn** [comment]
That example blames the *user* of the module, not the module.  In other words, / doesn't live up to the integer? integer? -> integer? contract, so you gave foo a bad input.  This program looks safe to me.

**Comment by philnguyen** [comment]
Yea, so in this case, `foo` is responsible for the following positions in the contract:

    ((integer? integer? . -> . _) _ . -> . integer?)

And the `foo`'s user is responsible for the other positions, including the `/` argument's range.

**Comment by cmentzer** [comment]
Understood, that makes perfect sense. I'll take this issue down in a minute.
