### ISSUE TITLE
PLDI artifact

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#52]
The README needs to have more information about _what_ the artifact is, i.e. clearly define what we are contributing as an artifact so a reviewer can verify that we deliver on that.

We should give the reviewer options for how to verify the artifact that include 1) using the web server hosted on scv.umiacs.umd.edu, 2) using the VM image we provide, and 3) building the software on their own system.

The directory structure should be simplified.

We need to include the accepted version of the paper.

**Comment by philnguyen** [comment]
(done long ago ^_^)
