### ISSUE TITLE
Guidance on testing

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#55]
In addition to telling reviewer how to run tests, we need to describe what is happening, ie there is a collection of programs being verified, followed by a collection for which counterexamples are generated.  

We should include in the repository a file containing the output of running the tests so they know what to expect.

We should include a statement about how long running the tests should take (roughly) when run in the virtual box on a laptop.

We should give some information about what would happen if a test case were to fail -- ie how does the reviewer know the results are all successful?  (There are summary numbers at the end: 341 tests passed.  If they see something different, something failed; we should set that expectation.)

We should give some warning about tests that take a while.  The last thing we want is for a reviewer to give up because there's no feedback during a long test.   There are only a few, so I suggest we update the test harness to print a warning before running each of those particular tests.  "Now test foo which is known to take up 5 minutes to test...".  Even better would be to spawn a thread that prints "." every 10 seconds just to let them know it's making progress.  (But if that's too much trouble, let's not worry about it.)

**Comment by philnguyen** [comment]
(done long ago ^_^)
