### ISSUE TITLE
Revert change to directory structure and redo

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#56]
It's never the right move if 700+ programs have to be changed to implement a simple directory restructure.

Please revert accfd308bb79edf296e70da5dbef22561555e088 and implement this change by either
- putting all of the source code in a top-level directory called soft-contract/ and changing the linking instructions to use this directory (i.e. soft-contract/soft-contract)
- putting all of the source code in a top-level directory called src/ and changing the linking instructions to provide the name soft-contract.

In either case, none of the code should change!  It should just be moved.  There should also be no rkt files in the root directory.

**Comment by philnguyen** [comment]
The test files `.sch` weren't changed, they were only moved. But I'll create a `soft-contract` subdirectory and move files there so no `.rkt` file appears at the top-level. Is that ok?

**Comment by dvanhorn** [comment]
On 2/13/15 12:53 AM, Phil Nguyen wrote:
> The test files |.sch| weren't changed, they were only moved. But I'll
> create a |soft-contract| subdirectory and move files there so no |.rkt|
> file appears at the top-level. Is that ok?

Ah my bad; sorry!  I saw the diff on main.rkt and assumed the require
line change was duplicated 700 times.  Yes if you move remaining .rkt
files into soft-contract subdirectory that will be OK.

**Comment by philnguyen** [comment]
(stale)
