### ISSUE TITLE
Handle struct-out

### ISSUE THREAD

**Issue by dvanhorn** [philnguyen/soft-contract#60]
Currently the tool can't handle `struct-out' provides.

**Comment by philnguyen** [comment]
The `struct-out` doesn't give enough information to verify (e.g. field count and names), so I'll just print out warnings that the `struct-out` form is ignored. The system does support the counterpart `struct` export in `contract-out`.

**Comment by dvanhorn** [comment]
That seems like an improvement.  Thanks!
