### ISSUE TITLE
Copying to temp files breaks `require`

### ISSUE THREAD

**Issue by wkunkel** [philnguyen/soft-contract#65]
### main.rkt
```racket
#lang racket

(require "example.rkt")
```
### example.rkt
```racket
#lang racket
```
### main.rkt
```
Safe
```
### main.rkt
```
/var/tmp/scv_strawman_14922940111492294011111.rkt:4:9: cannot open module file
  module path: #<path:/var/tmp/example.rkt>
  path: /var/tmp/example.rkt
  system error: No such file or directory; errno=2
  context...:
   standard-module-name-resolver
   /home/will/research/soft-contract/soft-contract/parse/expand.rkt:59:0: do-expand
   /home/will/research/soft-contract/soft-contract/parse/private.rkt:28:25: file->module
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/utils/simple-result-arrow.rkt:60:15
   /home/will/research/soft-contract/soft-contract/parse/main.rkt:11:0: file->module
   /home/will/research/soft-contract/soft-contract/run.rkt:30:0: havoc-files
   /home/will/research/soft-contract/soft-contract/cmdline.rkt: [running body]
```

**Comment by philnguyen** [comment]
Obviously I never tested multiple files that much and fixed a bunch of problems that showed up.

Anyways, I semi-fixed this: to verify multiple files, you'll need to insert `(require soft-contract/fake-contract)` into each file. After that, you can feed them as arguments to `cmdline.rkt` in any order. (If you forget to insert the line, it'll error asking you to do so).

By default, it'll verify each file you give. If you only want to verify the last file in the argument list, use `-l` or `--last-only`. You'll always need to pass any file that's part of dependency (it'll ask you to include each specific file that it needs). This may be annoying if they're lots of them, but for now that's the only way I know to figure out the contracts, sorry ^_^
