### ISSUE TITLE
cannot parse identifier

### ISSUE THREAD

**Issue by bennn** [philnguyen/soft-contract#85]
If certain identifiers appear in a module, `raco scv` raises an error that it "cannot parse [the] identifier". The identifiers I've found are:
- `exn:fail?`
- `make-immutable-hash`

I grepped for the error message & found `soft-contract/private/parse.rkt`, but didn't see an obvious way to fix this issue.

Example program:
```
#lang racket
exn:fail?
```

Error message:
```
foo.rkt:3:0: parser: don't know how to parse identifier
  in: exn:fail?
  context...:
```

**Comment by philnguyen** [comment]
This will be a  recurring error, as I will likely have some primitives unimplemented. In a perfect world, the primitive DSL is straightforward and anyone can add stuff to it. But it is gross for now.

I edited the error message to be less confusin.
