### ISSUE TITLE
match pattern (list null null) raises exception

### ISSUE THREAD

**Issue by bennn** [philnguyen/soft-contract#88]
### Example program
```
#lang racket

(define (f x)
  (match x
    ((list null null) #false)
    (_ #true)))

(provide (contract-out (f (-> (listof integer?) boolean?))))
```

I expected this would be Safe. Changing `(list null null)` to `(list '() '())` makes the program Safe.

### Error message

```
σ@: no address #(struct:-α.wrp #(struct:-𝒾 match-equality-test /Users/ben/code/racket/fork/racket/collects/racket/match/runtime.rkt))
  context...:
```

**Comment by bennn** [comment]
Using `with-handlers` gives a similar "no address" exception about `break-key-enabled`

```
#lang racket

(define (f x)
  (with-handlers ((exn:fail? (lambda (e) #false)))
    (and (x 0) #true)))

(provide (contract-out (f (-> (-> integer? integer?) boolean?))))
```

#### Error message
```
σ@: no address #(struct:-α.wrp #(struct:-𝒾 break-enabled-key #%paramz))
  context...:
````

**Comment by philnguyen** [comment]
Just a side note that `null` here is just a new variable, not the empty list.

For this small modified program, SCV can actually prove that the first clause would be unreachable if it was matched against `(list (list) (list))`. But I don't expect it to be predictable for more complicated ones.
```racket
#lang racket

(define (f x)
  (match x
    ((list (list) (list)) #false)
    (_ #true)))

(provide (contract-out (f (-> (listof integer?) values))))
```
